### ISSUE TITLE
AdipoQuant: qupath.imagej.objects.ROIConverterIJ

### ISSUE THREAD

**Issue by EST09** [Naveiras-Lab/MarrowQuant#4]
Hi, 

Thank you for this tool. I'm trying to use the 0.4.3 version but I get "It looks like you've tried to import a class 'qupath.imagej.objects.ROIConverterIJ' that couldn't be found". BoneMarrowQuant works well. Thank you!

Best wishes, 
Emily

**Comment by MarcHarford** [comment]
Hiya Emily, 

I´m currently using the same software and it is a fantastic however I wonder if you had any issue with the colour deconvolition section of the script? More specifically that trying to import it but it cannot be found even when specifying the directory? 

Many thanks, 
Marc

**Comment by EST09** [comment]
Hi, 

I don't remember having that issue - but I was only interested in adipocytes so that's probably why? 

For adipocytes I used: https://github.com/Naveiras-Lab/MarrowQuant2.0/tree/main and the stardust on adipocyte section
with qupath version 0.5.0 (on a mac). 

Sorry I don't think this is super helpful to your question. 

It's a fantastic tool for adipocytes though - thanks!

Best wishes, 
Emily

**Comment by MarcHarford** [comment]
Hiya, 

Thank you so much for a quick response. All help is great help!. I too am only interested in adipocytes both within the bone marrow and also from WAT sections yet I run into the deconvoluation error in addition to the error you posted previously. 

Many thanks for your time and help. 

Best regards, 
Marc

**Comment by EST09** [comment]
Hm - I remember this section in the readme being a little finicky (Setting up QuPath 0.3.1 for MarrowQuant) esp point 7 in https://github.com/Naveiras-Lab/MarrowQuant2.0 - maybe check that paths are pointing to the right places? I'm not too sure otherwise sorry. Hope that helps!

**Comment by MarcHarford** [comment]
You´ve been amazing thank you!
